### PR TITLE
Solve erratic "Errno::ENOENT: No such file or directory" on the fileutils.rb stat method

### PR DESCRIPTION
**Pull request by cavi21**
Hi! since I include this processor in our flow, I being experiencing the return of errors randomly, like this one below:

```
An Errno::ENOENT occurred in background at 2015-02-02 20:49:32 UTC :

  No such file or directory - /tmp/83adcf1ccdc34521790435a27d35c13420150202-29204-19pmkse20150202-29204-17joo6a20150202-29204-kqducm
  /usr/lib64/ruby/1.9.1/fileutils.rb:1515:in `stat'

  -------------------------------
Backtrace:
-------------------------------

  /usr/lib64/ruby/1.9.1/fileutils.rb:1515:in `stat'
  /usr/lib64/ruby/1.9.1/fileutils.rb:1515:in `block in fu_each_src_dest'
  /usr/lib64/ruby/1.9.1/fileutils.rb:1531:in `fu_each_src_dest0'
  /usr/lib64/ruby/1.9.1/fileutils.rb:1513:in `fu_each_src_dest'
  /usr/lib64/ruby/1.9.1/fileutils.rb:395:in `cp'
  /data/shared/bundled_gems/ruby/1.9.1/gems/paperclip-4.2.1/lib/paperclip/io_adapters/abstract_adapter.rb:42:in `copy_to_tempfile'
  /data/shared/bundled_gems/ruby/1.9.1/gems/paperclip-4.2.1/lib/paperclip/io_adapters/file_adapter.rb:13:in `cache_current_values'
  /data/shared/bundled_gems/ruby/1.9.1/gems/paperclip-4.2.1/lib/paperclip/io_adapters/file_adapter.rb:5:in `initialize'
  /data/shared/bundled_gems/ruby/1.9.1/gems/paperclip-4.2.1/lib/paperclip/io_adapters/registry.rb:29:in `new'
  /data/shared/bundled_gems/ruby/1.9.1/gems/paperclip-4.2.1/lib/paperclip/io_adapters/registry.rb:29:in `for'
  /data/shared/bundled_gems/ruby/1.9.1/gems/paperclip-4.2.1/lib/paperclip/attachment.rb:528:in `post_process_style'
```

And I dig a lot to found the possible root of the problem, the thing is the way the [**make**](https://github.com/janfoeh/paperclip-optimizer/blob/master/lib/paperclip-optimizer/processor.rb#L14) method is implemented on this processor.
I change a few things in order to mimic the way the native [**Thumbnail**](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/thumbnail.rb) processor work in paperclip, using the [**Tempfile**](http://ruby-doc.org//stdlib-1.9.3/libdoc/tempfile/rdoc/Tempfile.html) ruby library.

Since I change this I no longer get the error above.

Hope this helps, and please if there is anything else, or maybe if I miss something please don't hesitate to let me know!

Have a nice week!

### CODE REVIEW

**Comment by janfoeh** [comment]
Hi, thanks for taking the time to write a pull request! After looking into Paperclips [attachment.rb](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/attachment.rb#L521), I think I know what's going on:

Paperclip expects processors to return new file objects. PO usually does that - except when image_optimizer fails (line 34, `return @file`). In that case I hand back the original file, Paperclip closes it and later tries to access it again.

If that's true, it should be enough to replace only line 34 with `return File.new(@file.path)`. This way we could avoid the overhead of needlessly creating an additional tempfile in most cases.

Would you mind giving that a shot and see if that solves your problem as well?

**Comment by cavi21** [comment]
Hi @janfoeh thanks for the feedback! no worries, I'm going to try it and let you know

**Comment by cavi21** [comment]
@janfoeh me again! a few things, the **@file** returns correctly a **File** object, but regardless that, my solution was not working with some validations, I'm still testing a few things.

But as a insight I include some "puts" in order to see the output and this is what I got:
```
... GOT COMPRESSED - #<ImageOptim::ImagePath:/tmp/95c58b063ed0fcec54e9729aebef0f6220150225-19821-u99dzu20150225-19821-tqrj4820150225-19821-fxbpy7>
... JUST RETURN FILE - #<File:0x007fcf62f22dd8>
... JUST RETURN FILE - #<File:0x007fcf644c6c98>
... JUST RETURN FILE - #<File:0x007fcf645b68b0>
... JUST RETURN FILE - #<File:0x007fcf6467d938>
... GOT COMPRESSED - #<ImageOptim::ImagePath:/tmp/b0d096212dee1f2a95fd521c8775f5c120150225-19821-x3jnfp20150225-19821-prj4py20150225-19821-1oxcyy2>
... GOT COMPRESSED - #<ImageOptim::ImagePath:/tmp/b0d096212dee1f2a95fd521c8775f5c120150225-19821-x3jnfp20150225-19821-11obn9520150225-19821-13llbhl>
... GOT COMPRESSED - #<ImageOptim::ImagePath:/tmp/b0d096212dee1f2a95fd521c8775f5c120150225-19821-x3jnfp20150225-19821-far01220150225-19821-1kbbxp2>
... GOT COMPRESSED - #<ImageOptim::ImagePath:/tmp/b0d096212dee1f2a95fd521c8775f5c120150225-19821-x3jnfp20150225-19821-72o7qw20150225-19821-dbep81>
... GOT COMPRESSED - #<ImageOptim::ImagePath:/tmp/b0d096212dee1f2a95fd521c8775f5c120150225-19821-x3jnfp20150225-19821-18rt8ze20150225-19821-1oemfqi>
Errno::ENOENT: No such file or directory - /tmp/b0d096212dee1f2a95fd521c8775f5c120150225-19821-x3jnfp20150225-19821-18rt8ze20150225-19821-1oemfqi
from /usr/lib64/ruby/1.9.1/fileutils.rb:1515:in `stat'
```
and as you can see over there the error of **No such file or directory** is on an image that it was processed by ImageOptim so the return line is the one with
```ruby
return File.open(compressed_file_path)
```

I'm still digging in order to see if I can explain the error a little bit more!
If you have any comment, let me know, 

Thanks

**Comment by janfoeh** [comment]
That's quite puzzling… thanks for digging deeper! I'd be grateful for anything else you can turn up.

**Comment by janfoeh** [comment]
Out of curiosity, which optimizers do you have enabled? Is there a pattern, ie. is the error only occurring on a specific format? Is it reproducible with the same uploaded image?

**Comment by cavi21** [comment]
Yes, is very very weird! still not sure what's the issue exactly. 

I have this setup:
```ruby
Paperclip::PaperclipOptimizer.default_options = {
  skip_missing_workers: true,
  advpng: true,
  gifsicle: true,
  jhead: true,
  jpegoptim: true,
  jpegrecompress: true,
  jpegtran: true,
  optipng: true,
  pngcrush: false,
  pngout: false,
  pngquant: false,
  svgo: false
}
```
When I have a few styles declared in the attachment very few time I experience this issue, but on another attachment in which I have 10 styles declared I randomly got this errors. And like the :cherries: on top of the :cake:, if I reprocess the same attachment pass ok without issues sometimes. 

I tried several file formats, and there were randomly fails on different types

Still looking

**Comment by cavi21** [comment]
hi @janfoeh after reviewing a lot and trying to isolate the issue, in order to know if it was because the amount of styles, temp files, multithreading, or any other. I think I couldn't deeply understand the problem. But one thing that I know is that by applying this changes in the [processor.rb](https://github.com/cavi21/paperclip-optimizer/blob/821c25be86d58c8ee5cb58fae910a8e738462386/lib/paperclip-optimizer/processor.rb#L38)
```ruby
      if compressed_file_path && File.exist?(compressed_file_path)
        dst = Tempfile.new(@basename)
        dst.binmode
        compressed_file = File.open(compressed_file_path)
        compressed_file.rewind
        dst.write(compressed_file.read)
        compressed_file.close
        return dst
      else
        return @file
      end
```
The issue that I was experiencing disappear.

Also you will notice the ``compressed_file.rewind`` that I have to properly make sure that the pointer on the ``dst.write`` operation was in the beginning, to be real I think that probably I'm missing something because the solution I'm proposing looks __ugly__ on my perspective, so if you don't feel confortable merging this, no worries, and if anyone have the time and patience to debug this if they encounter the same issue, I'm happy to help on any way.

In my [master branch](https://github.com/cavi21/paperclip-optimizer/blob/master/lib/paperclip-optimizer/processor.rb) I have this change pushed, if there is anyone that needs it.

I tried to avoid creating a Tempfile if there is no ``compressed_file`` and FYI, I also review the ``/tmp/...`` directory and the files are cleaning up correctly so there are not temp files left behind.

Hope this helps to someone, and sorry about any inconvenience.
Have a great week!

**Comment by janfoeh** [comment]
PaperclipOptimizer is now EOL.

For maintained alternatives, have a look at https://github.com/kreeti/kt-paperclip and https://github.com/loco2/kt-paperclip-optimizer .

**Pull request closed without merging**
